# Generated by Django 5.2.7 on 2025-11-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_x1_pared_x_rename_y1_pared_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='pared',
            name='ancho',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pared',
            name='largo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
