# Generated by Django 5.2.7 on 2025-11-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_pared_ancho_pared_largo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('direccion', models.CharField(max_length=1)),
                ('vector', models.BooleanField()),
                ('imagen_fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.imagenfondo')),
            ],
        ),
    ]
