# Generated by Django 5.2.7 on 2025-11-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_bala'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='colision',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaje',
            name='direccion',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
